name: MinecraftServer
version: '1.0' # Enclosed version in quotes
main: com.example.minecraftserver.Main
api-version: '1.21'
# author: YourName # Optional
# description: A Minecraft plugin with PvP and Parkour games. # Optional

commands:
  game:
    description: Main command for games and game menu.
    usage: "/game <menu|join|leave> [gameType]"
    aliases: [games, play] # Added 'play' alias
